#!/usr/bin/env php
<?php
// I will allow you to use the command line to interact with DAVE.  Pass params with standard command line-style input (ie: --key1=val1 --key2=val2 OR -key1=val1 -key2=val2).  Variables passed this way will be available in $_GET, $_POST, $_COOKIE, and $_POST.

require("API/helper_functions/parseArgs.php");

$__args =  __parseArgs();
$__args["IP"] = "Console";
if (empty($__args["OutputType"]))
{
	$__args["OutputType"] = "CONSOLE";
}

$_GET = $_POST = $_COOKIE = $_REQUEST = $__args ;
unset($__args);

require("API/index.php");

?>